gems: [bourbon, neat]

# Structure configuration
source: source
destination: build

assets:
cachebust: soft

# Site settings
title: Huboard Enterprise
description: Documentation Portal for Huboard Enterprise

# Build settings
markdown: kramdown

# Include Pages Directory
include: [pages, images, hb-articles]

# Indicates Collections (Where Document Articles are)
