gems: 
  - bourbon
  - neat
  - jekyll-html-pipeline
  - extended-markdown-filter
  - jekyll-lunr-js-search

# Structure configuration
source: source
destination: build
host: 0.0.0.0

assets:
cachebust: soft

# Site settings
title: Huboard Enterprise
description: Documentation Portal for Huboard Enterprise

# Build settings
markdown: HTMLPipeline

html_pipeline:
  filters:
    - "ExtendedMarkdownFilter"
  context:
    emf_use_blocks: true

# Include Pages Directory
include: [pages, images, hb-articles]

# Indicates Collections (Where Document Articles are)
